name: Delete All Issues

on:
  workflow_dispatch:

jobs:
  delete-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure GitHub CLI is available
        run: gh --version

      # Option 1: Rely on GH_TOKEN from the environment (no explicit auth step)
      - name: Delete all issues
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Listing all issues in the repository..."
          # Fetch up to 1000 issues (both open and closed) and extract their numbers.
          issues=$(gh issue list --state all --limit 1000 --json number --jq '.[].number')
          echo "Found issues: $issues"
          
          for issue in $issues; do
            echo "Attempting to delete issue #$issue..."
            gh issue delete "$issue" --confirm || echo "Could not delete issue #$issue"
          done
          echo "Deletion process complete."
