name: Delete All Issues

# This workflow is triggered manually.
on:
  workflow_dispatch:

jobs:
  delete-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure GitHub CLI is available
        run: gh --version

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Delete all issues
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Listing all issues in the repository..."
          # List all issues (both open and closed) and extract their numbers.
          issues=$(gh issue list --state all --json number --jq '.[].number')
          echo "Found issues: $issues"
          
          for issue in $issues; do
            echo "Attempting to delete issue #$issue..."
            # The --confirm flag bypasses interactive confirmation.
            gh issue delete "$issue" --confirm || echo "Could not delete issue #$issue"
          done
          echo "Deletion process complete."
